services:
  messe-basse-production:
    container_name: rich_art_music_node
    build: .
    command: npm run start
    restart: always
    ports:
      - 8065:8065
    environment:
      - NODE_ENV=prod
